# Generated by Django 5.2.6 on 2025-09-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('catagory_image', models.ImageField(blank=True, upload_to='photos/catagories')),
            ],
            options={
                'verbose_name': 'Catagory',
                'verbose_name_plural': 'Catagory',
                'ordering': ['catagory_name'],
            },
        ),
    ]
